[package]
name = "linearsort"
description = "Sorting in linear time 🤔"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
license = "Unlicense OR MIT OR Apache-2.0"
version = "1.2.3"
edition = "2021"
rust-version = "1.70"

keywords = ["linear", "sort"]


[dependencies]
